wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.6.13
    cli_version: 0.15.11
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1712808587.09318
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 13
      - 23
      4: 3.6.13
      5: 0.15.11
      8:
      - 3
      - 5
      13: windows-amd64
